name: overcooked_admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # form_inputs:
  #   path: packages/form_inputs
  table_repository:
    path: packages/table_repository
  order_repository:
    path: packages/order_repository
  food_repository:
    path: packages/food_repository
  authentication_repository:
    path: packages/authentication_repository
  category_repository:
    path: packages/category_repository
  user_repository:
    path: packages/user_repository
  print_repository:
    path: packages/print_repository

    
  awesome_dialog: ^3.2.0
  equatable: ^2.0.5
  firebase_auth: ^4.16.0
  firebase_core: ^2.25.0
  flex_color_scheme: ^7.3.1
  flutter_spinkit: ^5.2.0
  go_router: ^13.1.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  firebase_messaging: ^14.7.11
  intl: ^0.19.0
  cloud_firestore: ^4.15.0
  fluttertoast: ^8.2.4
  logger: ^2.0.2+1
  flutter_bloc: ^8.1.3
  flutter_animate: ^4.5.0
  tiengviet: ^1.0.0
  readmore: ^2.2.0
  dotted_border: ^2.1.0
  firebase_storage: ^11.6.6
  freezed_annotation: ^2.4.1
  freezed: ^2.4.7
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.66.2
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1
  file_picker: ^8.0.0+1
  collection: ^1.18.0
  formz: ^0.7.0
  percent_indicator: ^4.2.3
  image: ^4.1.7
  image_picker: ^1.1.0
 
 
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true



  assets:
    - assets/map_style.txt
    - assets/image/
    - assets/image/banner/
    - assets/image/plate_food/
    - assets/image/image_recipe/
    - assets/icon/
    - assets/.env




flutter_native_splash:
  android: true
  ios: true
  web: true
  background_image: assets/image/splash.png
  image: assets/image/icon_splash.png
  android_12:
    image: assets/image/icon_splash.png
    icon_background_color: "#ffffff"
    image_dark: assets/image/icon_splash.png
    icon_background_color_dark: "#121212"



flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon_launcher.png"
  
  web:
    generate: true
    image_path: "assets/icon/icon_launcher.png"
  # image_path: "assets/icon/icon_launcher.png"
