class AppString {
  AppString._();
  static String authenticationFailure = 'Authentication Failure';
  static String welcomeBack = 'Đăng nhập';
  static String welcome = 'Tạo tài khoản';
  static String noAccount = 'Chưa có tài khoản?';
  static String signup = ' Đăng ký';
  static String invalidEmail = 'email không hợp lệ';
  static String email = 'Email';
  static String invalidPassword = 'mật khẩu không hợp lệ';
  static String password = 'mật khẩu';
  static String login = 'Đăng nhập';
  static String signInGoogle = 'SIGN IN WITH GOOGLE';
  static String signupFailure = 'Sign Up Failure';
  static String createAccount = 'Create Account';
  static String haveAnAccount = 'Đã có tài khoản?';
  static String signin = ' Đăng nhập';
  static String invalidName = 'invalid name';
  static String name = 'Name';
  static String nameEmpty = 'Name can\'t be empty';
  static String invalidPhone = 'invalid phone';
  static String phone = 'Phone';
  static String passwordDoNotMatch = 'passwords do not match';
  static String comfirmPassword = 'Confirm password';
  static String registerSuccessTitle = 'Register Success!';
  static String registerFailureTitle = 'Register Failure!';
  static String continueText = 'Continue';
  static String getStarted = 'Get started';
  static String passwordEmpty = 'Password can\'t be empty';
  static String emailEmpty = 'Email can\'t be empty';
  static String warning = 'Warning!';
  static String noInternet = 'No internet';
  static String loginWithEmail = 'Login with email';
  static String errorTitle = 'Error!';
  static String searchFood = 'Tìm kiếm món ăn';
  static String addToCart = 'Thêm vào giỏ hàng';
  static String dontSelectTable = 'Chưa chọn bàn, quay lại trang chủ chọn bàn.';
  static String ok = 'Ok';
  static String cancel = 'Cancel';
  static String totalPrice = 'Tổng tiền:';
  static String addedToCart = 'Đã thêm vào giỏ hàng.';
  static String priceSell = 'Giá bán';
  static String addNoteToChef = 'Thêm ghi chú cho đầu bếp';
  static String note = 'Ghi chú:';
  static String quantity = 'Số lượng';
  static String deletedSuccess = 'Đã xóa!';
  static String success = 'Success!';
  static String createAccountSuccess = 'Create account success!';
  static String goToLogin = 'Go to login';
  static String notPermission = 'Tài khoản không có quyền sử dụng!';
  static String titleManage = 'Quản lý';
  static String needCreateAccountAdmin =
      'Bạn cần tạo 1 tài khoản quản trị để có thể sử dụng.';

  static String titleFoodDetail = 'Chi tiết món ăn';
  static String titleOrder = 'Đơn hàng';

  static String tableStatusOccupied = 'occupied';
  static String tableStatusAvailable = 'available';
}
